/**
 * How to read the output. Written for a model. `layout-lens --legend` prints it, and the
 * `layout_legend` MCP tool serves it. It never changes, and no report repeats it.
 */
export const legend = `legend
  all numbers are px. one line per element: tag#id.class "first four words of its own text" WxH (border box), then tags. a shadow host has no words of its own, so it previews what its shadow tree shows. the tree is the rendered one, open shadow roots and slots included. no tag = nothing to say. first line: viewport, how far the page is scrolled down, full page size, painted to = how far down the page anything is actually drawn (a page 4000 tall painted to 200 is a shell, and what a scroll box holds below its own edge is not drawn), status 403 = the server answered that, only when it was not a 2xx, device pixel ratio, then ltr, start is left or rtl, start is right. start and end everywhere below are that way round.
  several viewports = the page was measured once at each, so there is a first line, a since last run and a summary for every one of them, then across viewports: 390 only: div.card: clipped right 12 = a finding at that width and not at the others, all: 12 findings shared = that many were on every width. two findings are compared on their kind, their element and the other element they name, with every number, every percentage and the element's own words taken out. the trees come after, each under a viewport 390x844 heading.
  the first line always ends with the color scheme the page was rendered in, light or dark. both schemes = the page was measured once in each, the same way as several viewports, then across schemes: dark only: span.hint: contrast 3.1 under 4.5 = a finding in one scheme and not in the other, and each tree heading names its scheme.
  could not load <target>: <reason> as the only line = the page never loaded, after a retry. nothing was measured. --timeout sets how long the load waits, 30000 ms by default. the network then gets a quarter of that to go quiet and the page is measured either way, since a page that polls never goes quiet.
  could not launch chromium, run: npx playwright install chromium as the only line = the browser itself is missing. playwright downloads it separately from the package.
  status 403 on the first line and server answered 403 as a finding = the server did not answer with a 2xx. what was measured is a block page or an error page, not the page that was asked for.
  scroll locked by div.dialog on the first line = html or body has overflow hidden and that dialog is open above the fold. the dialog has to paint something and be smaller than the viewport on one axis, an empty box the size of the screen is the host an app mounts overlays in. the page content hanging out of the frozen body is the lock working, so nothing reports being hidden by body or by html.
  measured after every animation and transition was finished, including scroll-driven ones. what you get is the settled layout.
  [shadow root] the element has an open shadow root, so the lines under it are its shadow tree, not its markup children. [shadow] = this element lives in a shadow tree. [slotted] = written in the page but drawn here, through a slot. everything else on the line, and every comparison with siblings and cousins, is measured on the tree as it renders.
  [shadow root closed] a custom element that draws a box with nothing in it to explain one. nothing inside can be reached, a closed shadow root is the likely reason. [shadow root skipped] = --no-shadow was passed, the markup children are shown instead.
  [renders] what it paints: background, border (or border-bottom etc for some sides), shadow, image. missing = paints nothing itself, it only holds text or children. an svg is a picture: nothing inside one is walked or measured, so it never reports its own shapes overflowing it and they never overflow anything above it. a chevron parked at x -10 and clipped by a clip-path of its own is drawing, not layout. contrast 1.4 with behind = its own background against the background painted behind it, said only when the ratio is under 3, which is where two areas start looking like the same color. a seat marked taken and a seat still free read the same at 1.4. only on a box with no words anywhere inside it: the color is the whole message on a swatch, and it is a tint behind the words on a table header or a button. left out when a picture or a gradient is behind it, the color there is a guess. this is about boxes, the contrast of the words is in [text].
  [scroll: y 568 in 300, bar 0, 15 of 25 children out] scrollable box: per axis, content size in visible size. bar = px the scrollbar takes, 0 = overlay scrollbar, takes no room. 15 of 25 children out = that many direct children are fully or partly outside the visible box, they say nothing on their own lines. the page itself is not a box, see page size on the first line.
  [pad: 16 8] padding, css shorthand order. children are measured inside it.
  [oversized] over 100000 px on one axis, which is how a code editor sizes its scrolling surface. nothing is said about it being clipped, overflowing or outside the viewport, and nothing it clips says so either. its children are measured as usual.
  [rotated 3°] the element is tilted. its box and its children's boxes are the upright bounding boxes of the tilted shape, so no centering or overlap findings inside it.
  [scaled 1.05] the element is drawn bigger or smaller than laid out. its children will not line up with the neighbours' children, so no alignment findings inside it.
  [sr-only] a box of 1x1, a box with no room inside it that hides what pokes out (1 px or less on either axis of its content box, with overflow hidden), or one clipped away to nothing, and kept for a screen reader. apple's nav labels are 1 px wide and 44 tall and the word you see beside them is drawn by an svg. [offscreen] = parked 10000 or more px off the page for the same reason. nothing else is measured on either, and their children are skipped. neither takes part in gaps, overlaps or alignment, and neither counts as ink: the words in a 1x1 clipped label are still laid out at full size and reach far outside it.
  [pos] where it sits inside the parent's content box (inside border and padding, where css centers things). absolute children are measured from the padding box, fixed ones from the viewport, the same boxes css places them from. block = vertical, inline = horizontal (start = left in ltr).
    one term per axis: fills-block = it touches the parent's top and bottom edges, fills-inline = the start and end ones. in a page written across, block is the up and down axis and inline is the one across. fills on its own = both of those at once, the element touches all four edges. centered-block 22 = centered, 22 above and 22 below, negative = same overhang both sides. never said for something stacked between siblings, which an absolute or fixed element never is. top 14 = 14 from the nearest edge, negative = pokes out.
    two terms on an axis, start 0, end 4 = alone on that axis, touches start, 4 short of end. a 0 on any of these means touching, there is no gap left.
    on a fixed element every term ends with of viewport, and both together are fills viewport. bottom 0 on a bar stuck to the screen is not the bottom of whatever holds it.
  [bleed 864] the element is wider (or taller) than the parent and hangs out by the same 864 on both sides. that even overhang is what makes it deliberate, a hero image running edge to edge under a padded page. a full-bleed hero was meant to do that: nothing about it being clipped, outside the viewport or overflowing is said on that axis, and its ancestors do not count it as content that overflows them.
  [gaps] space between neighbouring in-flow children, listed from start to end, which is right to left on an rtl page. text counts as a child. two children are neighbours along an axis when they share a band across the other one and nothing sits between them, so the last cell of a grid row and the first of the next are not neighbours and the drop between them is not a gap. 24 ×3 = three gaps of 24. twelve of them at most, … = there were more. omitted when all children touch. [gaps across] = the children sit side by side, plain [gaps] = they stack. children in more than one row and more than one column name both axes: rows 95, columns 16 ×4. seen 12, 9, 2, 11 = the same gaps measured a second way. the plain gaps are between the children's boxes. the seen gaps are between the ink, the nearest thing each child actually paints: a background, a border, an image, its words. two children whose boxes touch have a box gap of 0 and a seen gap of whatever their padding leaves between the words. only shown when the two differ. two painted areas that sit on top of each other are not spacing, so those gaps are left out and overlaps says it instead. twelve of them at most, … = there were more. 258 free after = room left inside a vertical stack after the last child, free before = before the first.
  [stacked 4] its children are all the same kind of thing and each is pulled onto the one before it by a negative margin, a row of overlapping avatars. sitting on each other is the design, so none of them overlaps, covers or hides another.
  [line: 2 inline children on one line] every element child is inline or inline-block and they all share one line, in a parent that is not flex or grid. two labels meant to sit one above the other read like this.
  [text] font used, size/line-height, ink top = box top to cap height, ink bottom = baseline to box bottom. the two being equal is what the eye reads as centered, whatever the numbers around them say. differ by more than 0.12em = text is visibly off center, reported as text off-center. when the element has element children too, both are measured against the element's own text lines instead of its box, a baseline measured past the children below the words means nothing. lines if wrapped, contrast ratio against the nearest painted ancestor background (4.5 min, 3 for large), reported as contrast 2.9 under 4.5, #878d96 on #f4f5f7 with the two colors it was measured from. contrast unknown, image behind = a picture or a gradient is behind the words, either an ancestor's background or a picture painted below them and covering them, and the color under it is a guess. a white heading on a stage photo used to read as #ffffff on the white section behind the photo. inside a code editor (role=textbox, contenteditable, a monaco, cm-content or ProseMirror class) the worst one is said once on the editor as ... on 45 text runs inside div.monaco-editor, and the tokens inside it get no alignment, overlap or off-center findings either. typed code is content, not ui.
  [not painted: opacity 0] has a box but nothing shows. children skipped.
  [children skipped] after the findings: nothing of it shows, so its subtree is not printed. a note, not a finding, and never counted as one.
  [!!] likely bugs, information not verdicts:
    off-center-block 4 down = center is 4 below the parent's center. only checked when it touches neither edge and no in-flow sibling sits before or after it on that axis.
    off-center-inline 13 toward start, siblings a.logo and select.version = the same thing for the middle one of a row of three, across the page. said only when the outer two touch the parent's two edges and the two gaps match, so the row spans it with one fixed gap between the three and the middle of the parent is the middle of the row. a row with a fixed gap puts the middle one off center as soon as the two sides come out different widths. over 8 and at most a quarter of the parent's content box on that axis: nothing else in the output says a row like that is off center, so any miss inside that range counts, and past a quarter the middle one is not near the middle at all and the row was laid out to some other plan. never said about a table cell, a table sizes every column to the widest thing in it and the middle of the row is not a place anyone aimed at. never said down a stack: a stack grows from the top and the middle of it sits where the height above it left it. never said about body, it is placed by the page itself. never said about a sticky element, it sits where scrolling left it. words count as a sibling, so a link in the middle of a sentence is never off-center. never said for an absolute or fixed element sitting closer to an edge than it is big, that one was pinned to the corner. no flag is not proof of centering.
    text off-center-block 2 up = the glyphs, not the box, sit 2 above the box center. never said about a table cell aligned to the top or the bottom: the cell is as tall as the tallest cell in its row and the words were put against an edge on purpose.
    top 12 covered by X = X paints on top of the top 12px. clipping comes first: only the part of the element that every ancestor still shows can be covered, so a row scrolled out of its scroll box is not covered by whatever sits below the box. never said about something drawn over its neighbours on purpose: one of a [stacked N], a sticky element over what it scrolls past, or a knob on a bar (an absolute box on a sibling under 8px thick). what a sticky element covers outside the box it scrolls in is still covered, and so is what it covers while its laid-out place is still fully inside the box it sticks in (the nearest ancestor that cuts its content off, or the viewport): it never had to move there, an offset pushed it off its place, and a table head with a top of 64 left over from a deleted nav bar sat on the first row of its own table. an element with pointer-events: none can be covered but never covers anything, a decorative canvas over a headline is not hiding it. 400x220 covered by X = a patch that size. all covered = nothing of it shows. (translucent) = X is see-through, a tint not a cover. a gradient is judged over the band where the two boxes actually meet, so a scrim fading to a solid color is a tint over the top of a hero and a cover over the bottom of it. (image) = X is a picture, and where a picture is transparent cannot be told apart from where it is not: reading its alpha means drawing it into a canvas, and a cross-origin image taints the canvas. so a picture on top is only ever this box fact, and the words under it may well be perfectly readable. (overlay) = X is absolute or fixed and lifted above the page, it was meant to sit on top. one coverer is named once down a branch: an element drops its covered by X when something under it says text or control hidden by X, those lines carry the words and the percentage.
    text "Devon Park" hidden by X = X sits on the words, not just on the box, so they cannot be read. 60% hidden = that much of the text area. an element whose box is covered but whose words are all clear says nothing.
    control "Send" hidden by X = a button, link or field is under X, so it cannot be clicked whatever its label reads. 40% hidden = that much of its box. a translucent X gets neither this nor text hidden, a tint hides nothing, it stays a covered by line. neither does a picture, for the same reason.
    clipped / scrolled out / outside viewport N = that many px of the element cannot be seen on that side, never how far past the edge it reaches, so a 168 wide bar fully off screen says 168. by X = who hides it. a direct child of a scroll box says neither, the box counts its children out instead. said once down a branch: only what pokes out further than the nearest line above it already said is said again.
    all clipped by X = clipping takes the whole element on one axis, a panel collapsed to nothing still holding its content. instead of the per-side numbers, which say nothing once none of it shows. X = the clipper, or parent. it says clipped, never covered: an ancestor cuts the element away, it never paints on top of it.
    div.widget hides 45 more elements = one clipper took more than ten. the first ten say it on their own lines, the rest are counted here, on the clipper.
    empty painted box = it paints a background or a border, holds no text and nothing that shows anywhere inside it, and what it paints is at least 24 px both ways. a background or four borders paint the whole box, a border on one or two sides paints a line as thick as the border: a column rule 1 px wide is a line, never a box, whatever its height. an ad slot that never filled, a band left behind by a section that was removed. never said about a knob on a bar, a slider thumb is empty because it is a thumb, nor for an absolute or fixed element covering 90% of the viewport, a backdrop behind a dialog is empty on purpose.
    same as 3 above = the same finding, with the same numbers, was already printed on three elements. the summary counts every one of them.
    content truncated N hidden at end = children reach N px past this box and it hides them, past the end edge, so that many px cannot be seen. measured from the padding box, which is where the cut happens. content overflows N at start = nothing hides them, and it is measured from the content box instead, which is where css laid the children out: a child ending past it is eating into the padding, and that is the number. at both = it pokes out on either side, and N is both sides added up. one side named on its own = N is that side's own spill. a side under 1 px is not spilling, and its px are never added onto the side that is. text truncated / text overflows = the same for the element's own text, and text truncated says ellipsis or no ellipsis, whether the cut was meant to look like one. measured from the element's own text lines and the children it lays out, never from scrollWidth, which counts a pseudo element and an absolute descendant too. an absolute or fixed descendant is left out however deep it sits, it is placed against a box of its own.
    text truncated 118 hidden below, content truncated 40 hidden above, hidden above and below = the same measurement down the page. above and below rather than start and end, a line cut off the bottom of a clamped paragraph did not run past the end of anything. only for a box that hides what pokes out of it, since a box that lets it through shows it and a box takes its height from what is in it, and a scroll box keeps it reachable. a child clipped by something under this box counts only as far as that clip lets it show, so a code line 959 wide in a 498 wide scroll box overflows nothing above it.
    110 free after, none in the sibling section.panel = this column has room left under its last child and the one beside it does not. it was stretched to match its neighbour and its content did not follow.
    uneven spacing, 2 between div.a and div.b, others 11 = one seen gap is under half the median of the other seen gaps, along one axis. only when there are three or more of them, they agree with each other (largest at most 3× the smallest), and the box gaps do not already say it. only one gap may break the rhythm: two that do is two rhythms mixed, not one gap gone wrong. never said when every box gap is the same and not zero, the spacing is fixed there and what is left between the painted areas is how wide the words came out. never said about the children of a table, which sizes every column to the widest thing in it. never said about children in more than one row and more than one column: a grid stretches every cell to its track and what a cell paints inside it is ragged, which says nothing about the spacing.
    218 free at end, on every row of this column = a column of a table, or of a grid, where every cell stops at least that far short of its own end edge. said once, on the first cell of the column. a measurement, not a verdict: the column may be that wide on purpose. measured on the ink, since a block child fills the cell whatever its words come out to. the hole has to be at least 48 and at least as wide as the widest thing in the column, so the column is more empty than full: every auto-width column leaves the shorter rows some room, and that is what a table looks like.
    overlaps X = partly shares area with the earlier sibling X, measured on what each of them draws rather than on their boxes. an element that paints a background, a border or a picture draws its whole box, one that paints nothing draws only its words and its children, and a line box is taller than the letters in it. so a heading and the line under it can have crossing boxes with clear air between the glyphs, and nothing is said. neither box holds the other. printed once, on the later one, and once per pair of names: a resizer overlapping the pane before it and the pane after it overlapping the resizer is one fact said one way. never said between the children of a [stacked N], about a sticky element and what it scrolls past, or when X already reports being covered or hidden by this one, that line said it. a slider thumb over its track is an overlap too. (overlay) = this one is absolute, so it was put on top on purpose. never said about a fixed element, on it or against it: the page runs under it as it scrolls and covered by says what it hides. never said about a floated or an inline element, text is meant to run around a float and an inline box sits where the words leave room.
    top edge 8 lower than a.button in article.card = same-looking things that should line up and nearly do. compared with the previous same-named sibling, and with the child in the same place in the parent's previous sibling (the card next door, the next column). the row next door is paired by place, not by name: one child named differently anywhere in a row used to shift every child after it by a place, and a seat grid with one taken seat in it printed seven misalignments that were not there. said once, on the odd one out: when the one before is already out of line by the same amount the other way, it is the odd one and its own line said it.
    2 wider than div.tile = the previous same-named sibling is a different size, by more than 1 and at most 8. only when the two carry exactly the same classes, show the same words and hold the same kinds of children. two buttons reading "Default" and "Primary" are different widths because the words are, and button.control.control-main is the big one in the middle of a transport bar on purpose.
  since last run: 5 gone, 2 new, 1 changed comes straight after the first line = against the previous run of the same page at the same size and scroll. - is a finding that went away, + is one that appeared, ~ is one whose only change is a number, written as element: changed, text truncated 74.5 to 156.5 hidden at end. first run = nothing to compare with yet. then the summary, then the tree.
  the summary: every kind of finding once, with its number or a range written as 47 to 497, a count, and up to three of the elements it is on. the findings on the first line count too, under the name page. contrast failures are grouped by the text color instead: #8b949e fails contrast on 3 backgrounds, 28 elements, worst 2.7 on #ffffff, one palette bug rather than one per background.
    content overflows / content truncated counts only what is drawn. a hidden dropdown reaching past the end of its row is not the row overflowing.
  ×3 after a line = three identical siblings, printed once, on the first of them. ×29 similar = twenty-nine more siblings of the same kind, painting and holding the same kinds of things, differing only in their words, their size and their offsets. which edges of the parent they sit flush against across the page is compared: two rows at different offsets are the same row, one touching the start edge where the others sit 16 in was put somewhere else. down the page is not compared, the first and last of a stack touch the parent's two edges by being first and last. the hidden siblings carry the same tags and the same findings as the shown one, so its [!!] is theirs too, and a sibling that goes wrong differently stays on its own line. only the first one's subtree is printed, and the summary above still counts every one of them. two siblings that only look alike are both printed, there is no ×1 similar.
  a › b = wrapper a paints nothing and only holds b, same size. three links at most, … › = deeper wrappers were dropped.
  names: two classes at most, each cut to 24 characters. a generated run at the end of a class or an id is dropped (Header__xm1jd = Header, sc-6cc20e4a-0 = nothing). div:nth-child(4) = the name says nothing about which element this is, because it has no id and no class, or only utility classes like pt-0.5 and col-start-4. its place among its siblings is the identifier instead, and only when a sibling shares its tag: the one aside in a page is just aside.
`;
